### ISSUE TITLE
Why we need to save SOMRegressor.p?

### ISSUE THREAD

**Issue by JimmyGao0204** [felixriese/susi#10]
In this notebook, why we need to save som to SOMRegressor.p in the local disk when the som has been trained?
Does anybody can explain this ?
Thank you.

**Comment by felixriese** [comment]
This is only for convenience, you don't need that.

Since training of the `SOMRegressor` can take some time, it makes sense to save the trained SOM for later tests without having to re-run the training over and over again. I can remove that part in a next commit.
