### ISSUE TITLE
ImportError: cannot import name 'softmax'

### ISSUE THREAD

**Issue by deepwindlee** [felixriese/susi#11]
ImportError Traceback (most recent call last) <ipython-input-1-dbfadab0ca4e> in <module>() ----> 1 import susi ~\Anaconda3\lib\site-packages\susi\__init__.py in <module>() 6 import numpy as np 7 import scipy.spatial.distance as dist ----> 8 from scipy.special import softmax 9 from sklearn.base import BaseEstimator, RegressorMixin, ClassifierMixin 10 from sklearn.decomposition import PCA ImportError: cannot import name 'softmax'

**Comment by felixriese** [comment]
Hi @deepwindlee , Please update your packages, especially scikit-learn and scipy with 

```
pip install --upgrade scikit-learn scipy
```

or via conda. Did that resolve your problem?

The required versions can be found in the [requirements.txt](https://github.com/felixriese/susi/blob/master/requirements.txt).
