### ISSUE TITLE
sklearn.utils.fixes.parallel_helper is removed in the latest version of sklearn

### ISSUE THREAD

**Issue by bramiozo** [felixriese/susi#12]
Hi Felix, thank you for what seems to be a great SOM implementation. Seems to be because I cannot import susi. It seems that sklearn has completely removed sklearn.utils.fixes.parallel_helper.

I think that Line 501 should become: ```delayed(self.get_bmu)(som_array, dp)```

Greetings,

Bram

**Comment by felixriese** [comment]
@bramiozo Thanks for finding and solving the issue! I have update the package, please upgrade to version 1.0.8 via

`pip install --upgrade susi`

and test the package as you wish. If the problem persists, please write me here. If there is another issue, please open a new issue on GitHub.
