### ISSUE TITLE
Multi-output regression for SOMRegressor?

### ISSUE THREAD

**Issue by thongjlj** [felixriese/susi#19]
Hi Felix,

I noticed that the fit function for SOMRegressor only allows y to be a matrix of shape = [n_samples, 1]. Is there any way to allow for multi-output regression using SOMRegressor?

Thank you!

**Comment by felixriese** [comment]
Hi @thongjlj ,

Can you please post a minimum reproducible example of what you want to do?

As you can see in this test, it should work: https://github.com/felixriese/susi/blob/master/tests/test_MultiOutput.py Maybe the documentation is lacking this information?

Best, Felix

**Comment by thongjlj** [comment]
Hi Felix,

Thanks for the link! Previously I couldn't figure out to do it but I managed to get it to work now with your help :)
