### ISSUE TITLE
SOMClassifier object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by bennydayana** [felixriese/susi#21]
If I need to plot AUC-ROC curve as in other ML techniques in SKLEARN, is there any function like predict_proba() ? or manually has to calculate? Because it returns 'SOMClassifier' object has no attribute 'predict_proba'... Is there any function for the same?

**Comment by felixriese** [comment]
@bennydayana Thanks for opening the issue.

Right now, there is no `predict_proba()` function, but I will have a look if it can be easily implemented.

**Comment by felixriese** [comment]
@bennydayana I have implemented the `SOMClassifier.predict_proba()` function as requested.

If you have time, please install the latest version and test it out. Afterward, I will put it on Pypi. This should work to install the latest version:

    pip uninstall susi
    git clone https://github.com/felixriese/susi.git
    cd susi/
    python setup.py install

Let me know if it works for you. If it does not work, please provide a minimal reproducible code example and the error message.

**Comment by bennydayana** [comment]
Thanks! It is perfect!!

**Comment by akol67** [comment]
> 
> 
> @bennydayana Thanks for opening the issue.
> 
> Right now, there is no `predict_proba()` function, but I will have a look if it can be easily implemented.

predict_proba() would be great for defining a theshold and avoiding problems with unbalanced data
