### ISSUE TITLE
Support for sparse matrix 

### ISSUE THREAD

**Issue by thunderbug1** [felixriese/susi#30]
Hi, thank you for the great package.
I just wanted to ask whether the support for sparse matrices is still on the roadmap? 
Some comments in the code suggest that it was planned.

**Comment by felixriese** [comment]
Hi @thunderbug1, thanks for your request! Sparse matrices are still on the roadmap, I didn't get to them yet.

Could you add a small example for a matrix or a dataset that you would like to use `susi` on? That could be helpful for the development and tests.

**Comment by felixriese** [comment]
Thanks! I will have a look as soon as I find time.

If it is urgent, PRs are also always welcome :)

**Comment by felixriese** [comment]
After some tests (thanks for the nice exemplary data, @thunderbug1, that helped a lot!) and thoughts, I decided will not pursue the implementation of handling such kind of sparse input (`X`) matrices for now. The reasons:

1. Meaningful adaptations are very difficult with such sparse data. If that is incorrect for a dataset, see 2.:
2. I guess that `mean` imputing sparse data (e.g., [`sklearn.impute.SimpleImputer`](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html)) can be a promising intermediate solution for the challenge of sparse data. I have not done the full research on this topic, but it feels intuitive to me.

I am open for corrections and further ideas, and (if course) own pull requests.

[closing this issue now, can be reopened if there is progress or new ideas]
