### ISSUE TITLE
Saving and loading SOM model

### ISSUE THREAD

**Issue by nfsrules** [felixriese/susi#32]
Hi there!

Does SUSI has a save/open dict method? If not, any ideas to do it quicky?

**Comment by felixriese** [comment]
Hi, what exactly do you mean with "save/open dict method"? What is in the dict? Can you give me an example?

**Comment by nfsrules** [comment]
som.fit(X)
som.save_model('my_model')

my_model = susi.load_model('my_model)

**Comment by felixriese** [comment]
Thanks @nfsrules! What is the advantage of this over just using `pickle`? 

```python
import pickle
...
som.fit(X)
pickle.dump(som, open("my_file.p", "wb"))
...
som = pickle.load(open("my_file.p", "rb"))
```

See also [this](https://scikit-learn.org/stable/model_persistence.html#python-specific-serialization) by scikit-learn about model persistence.
