### ISSUE TITLE
No placeholder defined

### ISSUE THREAD

**Issue by jalalnouri72** [felixriese/susi#50]
I ran [https://github.com/felixriese/susi/blob/main/examples/SOMClassifier_semisupervised.ipynb](url) code without any changes and I got the following error:

```
	"name": "ValueError",
	"message": "('No placeholder defined for the dtype of the classes:', <class 'numpy.int32'>)",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 11
      1 # NBVAL_IGNORE_OUTPUT
      4 som_semi = susi.SOMClassifier(
      5     n_rows=15,
      6     n_columns=15,
   (...)
      9     missing_label_placeholder=-1,
     10     random_state=42)
---> 11 som_semi.fit(X_train, y_train)
     12 y_pred = som_semi.predict(X_test)
     13 accuracy = metrics.accuracy_score(y_test, y_pred)

File c:\\Users\\BoJack_Human\\miniconda3\\envs\\conda_myBase_env\\Lib\\site-packages\\susi\\SOMClassifier.py:315, in SOMClassifier.fit(self, X, y)
    312 self.y_: np.ndarray = y
    313 self.n_features_in_ = self.X_.shape[1]
--> 315 return self._fit_estimator()

File c:\\Users\\BoJack_Human\\miniconda3\\envs\\conda_myBase_env\\Lib\\site-packages\\susi\\SOMEstimator.py:244, in SOMEstimator._fit_estimator(self)
    242 # train SOMs
    243 self._train_unsupervised_som()
--> 244 self._train_supervised_som()
    246 self.fitted_ = True
    248 return self

File c:\\Users\\BoJack_Human\\miniconda3\\envs\\conda_myBase_env\\Lib\\site-packages\\susi\\SOMEstimator.py:391, in SOMEstimator._train_supervised_som(self)
    389 \"\"\"Train supervised SOM.\"\"\"
    390 self._set_bmus(self.X_[self.labeled_indices_])
--> 391 self._init_super_som()
    393 if self.train_mode_supervised == \"online\":
    394     for it in tqdm(
    395         range(self.n_iter_supervised),
    396         desc=\"super\",
    397         **self.tqdm_params_,
    398     ):
    399         # select one input vector & calculate best matching unit (BMU)

File c:\\Users\\BoJack_Human\\miniconda3\\envs\\conda_myBase_env\\Lib\\site-packages\\susi\\SOMClassifier.py:205, in SOMClassifier._init_super_som(self)
    201 self.classes_, self.class_counts_ = np.unique(
    202     self.y_[self.labeled_indices_], return_counts=True
    203 )
    204 self.class_dtype_ = type(self.y_.flatten()[0])
--> 205 self._set_placeholder()
    207 # check if forbidden class name exists in classes
    208 if self.placeholder_ in self.classes_:

File c:\\Users\\BoJack_Human\\miniconda3\\envs\\conda_myBase_env\\Lib\\site-packages\\susi\\SOMClassifier.py:282, in SOMClassifier._set_placeholder(self)
    280     self.placeholder_ = self.placeholder_dict_[\"float\"]
    281 else:
--> 282     raise ValueError(
    283         \"No placeholder defined \" + \"for the dtype of the classes:\",
    284         self.class_dtype_,
    285     )

ValueError: ('No placeholder defined for the dtype of the classes:', <class 'numpy.int32'>)"
```

Can anyone guide me?

**Comment by jalalnouri72** [comment]
> I ran [https://github.com/felixriese/susi/blob/main/examples/SOMClassifier_semisupervised.ipynb](url) code without any changes and I got the following error:
> 
> `{ "name": "ValueError", "message": "('No placeholder defined for the dtype of the classes:', <class 'numpy.int32'>)", "stack": "--------------------------------------------------------------------------- ValueError Traceback (most recent call last) Cell In[3], line 11 1 # NBVAL_IGNORE_OUTPUT 4 som_semi = susi.SOMClassifier( 5 n_rows=15, 6 n_columns=15, (...) 9 missing_label_placeholder=-1, 10 random_state=42) ---> 11 som_semi.fit(X_train, y_train) 12 y_pred = som_semi.predict(X_test) 13 accuracy = metrics.accuracy_score(y_test, y_pred)
> 
> File c:\Users\BoJack_Human\miniconda3\envs\conda_myBase_env\Lib\site-packages\susi\SOMClassifier.py:315, in SOMClassifier.fit(self, X, y) 312 self.y_: np.ndarray = y 313 self.n_features_in_ = self.X_.shape[1] --> 315 return self._fit_estimator()
> 
> File c:\Users\BoJack_Human\miniconda3\envs\conda_myBase_env\Lib\site-packages\susi\SOMEstimator.py:244, in SOMEstimator._fit_estimator(self) 242 # train SOMs 243 self._train_unsupervised_som() --> 244 self._train_supervised_som() 246 self.fitted_ = True 248 return self
> 
> File c:\Users\BoJack_Human\miniconda3\envs\conda_myBase_env\Lib\site-packages\susi\SOMEstimator.py:391, in SOMEstimator._train_supervised_som(self) 389 """Train supervised SOM.""" 390 self._set_bmus(self.X_[self.labeled_indices_]) --> 391 self._init_super_som() 393 if self.train_mode_supervised == "online": 394 for it in tqdm( 395 range(self.n_iter_supervised), 396 desc="super", 397 **self.tqdm_params_, 398 ): 399 # select one input vector & calculate best matching unit (BMU)
> 
> File c:\Users\BoJack_Human\miniconda3\envs\conda_myBase_env\Lib\site-packages\susi\SOMClassifier.py:205, in SOMClassifier._init_super_som(self) 201 self.classes_, self.class_counts_ = np.unique( 202 self.y_[self.labeled_indices_], return_counts=True 203 ) 204 self.class_dtype_ = type(self.y_.flatten()[0]) --> 205 self._set_placeholder() 207 # check if forbidden class name exists in classes 208 if self.placeholder_ in self.classes_:
> 
> File c:\Users\BoJack_Human\miniconda3\envs\conda_myBase_env\Lib\site-packages\susi\SOMClassifier.py:282, in SOMClassifier._set_placeholder(self) 280 self.placeholder_ = self.placeholder_dict_["float"] 281 else: --> 282 raise ValueError( 283 "No placeholder defined " + "for the dtype of the classes:", 284 self.class_dtype_, 285 )
> 
> ValueError: ('No placeholder defined for the dtype of the classes:', <class 'numpy.int32'>)" }`
> 
> Can anyone guide me?

**Comment by felixriese** [comment]
@jalalnouri72 Does the problem still exist with the latest version of `susi`? If yes: which numpy version are you using?

**Comment by jalalnouri72** [comment]
Hi @felixriese . thanks for helping. yes, problem still exist.
I have these in my vitual env:
Python 3.11.9
numpy 1.24.3

**Comment by felixriese** [comment]
@jalalnouri72 It should be fixed with the latest version. Please update and let me know :)
