### ISSUE TITLE
Error with SOMClassifier_semisupervised example

### ISSUE THREAD

**Issue by hsynan** [felixriese/susi#51]
Hi, <br> I am looking to work with the semi-supervised classifier. I am trying to run [SOMClassifier_semisupervised.ipynb](https://github.com/felixriese/susi/blob/main/examples/SOMClassifier_semisupervised.ipynb) but getting an error `'No placeholder defined for the dtype of the classes', <class 'numpy,int32'>` at code cell 3, line 11 (`som_semi.fit(X_train, y_train)`). I haven't changed any part of the example code yet. Is this something that is able to be fixed? <br> Thank you!

**Comment by felixriese** [comment]
@hsynan It should be fixed with the latest version. Please update and let me know :)

**Comment by felixriese** [comment]
I released `1.4.2`, now this version should also work for you
